language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE test;'; fi"
  - mysql test < app/Config/Sql/init.sql
  - composer install --dev --no-interaction
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then composer global require 'phpunit/phpunit=3.7.33'; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ./vendors/PHPUnit; fi"
  - chmod -R 777 ./app/Console/cake
  - cp ./app/Config/database.php.travis ./app/Config/database.php

script:
  -  ./app/Console/cake test app AllApp --stderr
